// app/page.tsx
import Head from 'next/head';
import TaskManager from './components/TaskManager';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Task Manager</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-[#EBEAE6] min-h-[100vh] pt-10'>
        <TaskManager />
      </main>
    </div>
  );
}
